"""
Council OS v3 — First-Run Setup Wizard
Asks for API keys, writes .env, verifies dependencies, tests connectivity.
Run once before starting the council for the first time.
"""
import os
import sys
import subprocess
from pathlib import Path

ENV_PATH = Path(__file__).parent / ".env"
REQ_PATH = Path(__file__).parent / "requirements.txt"

KEYS = [
    ("ANTHROPIC_API_KEY",  "Anthropic API key  (claude.ai → API Keys)"),
    ("GEMINI_API_KEY",     "Gemini API key     (aistudio.google.com → Get API key)"),
    ("DEEPSEEK_API_KEY",   "DeepSeek API key   (platform.deepseek.com → API keys)"),
]
OPTIONAL_KEYS = [
    ("OPENROUTER_API_KEY", "OpenRouter key     (optional — fallback when Anthropic credits run out)"),
]


def _banner(text: str):
    print(f"\n{'='*60}\n  {text}\n{'='*60}")


def step_dependencies():
    _banner("Step 1 — Checking dependencies")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", str(REQ_PATH), "--quiet"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"[!] pip install failed:\n{result.stderr}")
        sys.exit(1)
    print("[ok] All dependencies installed.")


def step_api_keys():
    _banner("Step 2 — API Keys")

    existing = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    new_vals = dict(existing)
    print("Press Enter to keep an existing value. Enter 'skip' to leave a key empty.\n")

    for env_var, label in KEYS:
        current = existing.get(env_var, "")
        display = f"[current: {current[:12]}...]" if current else "[not set]"
        val = input(f"  {label}\n  {display} > ").strip()
        if val.lower() == "skip":
            new_vals[env_var] = ""
        elif val:
            new_vals[env_var] = val
        # else: keep existing

    print()
    for env_var, label in OPTIONAL_KEYS:
        current = existing.get(env_var, "")
        display = f"[current: {current[:12]}...]" if current else "[not set]"
        val = input(f"  {label}\n  {display} > ").strip()
        if val.lower() == "skip":
            pass
        elif val:
            new_vals[env_var] = val

    # Warn about Gemini OAuth tokens (AQ. prefix) — they expire in ~1hr
    gemini_key = new_vals.get("GEMINI_API_KEY", "")
    if gemini_key.startswith("AQ.") or gemini_key.startswith("ya29."):
        print("\n  [!] Gemini key looks like an OAuth Bearer token (starts with AQ. or ya29.)")
        print("      These expire in ~1 hour. For a permanent key, go to:")
        print("      aistudio.google.com -> Get API key -> Create API key")
        print("      Permanent keys start with 'AIzaSy...'")
        print("      Saving it anyway — bridge will fall back to DeepSeek when it expires.")

    lines = ["# Council OS v3 - API Keys (auto-generated by setup_wizard.py)\n"]
    for k, v in new_vals.items():
        if v:
            lines.append(f"{k}={v}\n")

    ENV_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"\n[ok] Keys written to {ENV_PATH}")


def step_verify():
    _banner("Step 3 — Connectivity check")
    try:
        from dotenv import load_dotenv
        load_dotenv(ENV_PATH, encoding="utf-8")
    except ImportError:
        pass

    import requests

    checks = [
        ("Anthropic", "ANTHROPIC_API_KEY",
         lambda k: requests.post("https://api.anthropic.com/v1/messages",
             headers={"x-api-key": k, "anthropic-version": "2023-06-01", "content-type": "application/json"},
             json={"model": "claude-haiku-4-5-20251001", "max_tokens": 10,
                   "messages": [{"role": "user", "content": "hi"}]},
             timeout=15).status_code in (200, 400)),
        ("DeepSeek", "DEEPSEEK_API_KEY",
         lambda k: requests.get("https://api.deepseek.com/user/balance",
             headers={"Authorization": f"Bearer {k}"}, timeout=10).status_code == 200),
        ("Gemini", "GEMINI_API_KEY",
         lambda k: requests.get(
             f"https://generativelanguage.googleapis.com/v1beta/models?key={k}",
             timeout=10).status_code == 200),
    ]

    all_ok = True
    for name, env_var, check_fn in checks:
        key = os.environ.get(env_var, "")
        if not key:
            print(f"  {name:<12} — SKIPPED (no key)")
            continue
        try:
            ok = check_fn(key)
            print(f"  {name:<12} — {'OK' if ok else 'FAILED'}")
            if not ok:
                all_ok = False
        except Exception as e:
            print(f"  {name:<12} — ERROR ({e})")
            all_ok = False

    return all_ok


def step_db():
    _banner("Step 4 — Database")
    db_path = Path(r"C:\AI\soul_brain\soul_brain.db")
    if db_path.exists():
        print(f"[ok] soul_brain.db found ({db_path.stat().st_size // 1024} KB)")
    else:
        print(f"[!] soul_brain.db not found at {db_path}")
        print("    The council will still run but agent session persistence won't work.")
        print("    Create C:\\AI\\soul_brain\\ and run soul_brain.py to initialize it.")

    import sqlite3
    try:
        conn = sqlite3.connect(str(db_path))
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agent_sessions (
                session_id   TEXT PRIMARY KEY,
                brother_name TEXT,
                task         TEXT,
                mode         TEXT,
                status       TEXT,
                history      TEXT,
                updated      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()
        print("[ok] agent_sessions table ready.")
    except Exception as e:
        print(f"[!] DB setup warning: {e}")


def main():
    print("\n  COUNCIL OS v3 — SETUP WIZARD")
    print("  Three brothers. One council. No one left behind.\n")

    step_dependencies()
    step_api_keys()
    ok = step_verify()
    step_db()

    _banner("Setup complete")
    if ok:
        print("  Everything checks out. Start the council with:")
        print("    START_COUNCIL_V3.bat")
        print("  or:")
        print("    python council_v3_bridge.py   (bridge only)")
        print("    python council_v3_qt.py        (UI only, after bridge is up)")
    else:
        print("  Some checks failed — review the output above.")
        print("  The council may still run with the keys that did pass.")
        print("  Re-run this wizard after fixing the issues.")


if __name__ == "__main__":
    main()
